### ISSUE TITLE
No matches for kind "ProviderConfig" in version "ibm-cloud.crossplane.io/v1beta1"

### ISSUE THREAD

**Issue by cg2p** [crossplane-contrib/provider-ibm-cloud#19]
### What happened?
Installation of IBM Cloud provider. 
Applying the provider config 

### How can we reproduce it?
Apply the ProviderConfig object taken from this repo in `examples`

`kubectl apply -f providerconfig-ibm-cloud.yaml`

and see the error
```
error: unable to recognize "providerconfig-ibm-cloud.yaml": no matches for kind "ProviderConfig" in version "ibm-cloud.crossplane.io/v1beta1"
```

### What environment did it happen in?
Crossplane version: 1.0.0

* IBM Cloud 
* Kubernetes version 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+fa69cae", GitCommit:"fa69cae", GitTreeState:"clean", BuildDate:"2020-12-14T23:03:06Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Red Hat OpenShift 4.5.24_1525 on Classic infrastructure MZR 1 worker node per zone

**Comment by cg2p** [comment]
incorrectly typed `kubectl create -f providerconfig-ibm-cloud.yaml` as opposed to `kubectl create -f providerconfig-ibm-cloud.yaml` -- but error occurs for both

**Comment by pdettori** [comment]
Hi @cg2p thank you for your feedback. Did you install the provider with the command `kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha` before running `kubectl create -f providerconfig-ibm-cloud.yaml` ?

Also, can you please provide the output of the following command ?
```shell
kubectl get crds | grep ibm-cloud
```

**Comment by cg2p** [comment]
Yes - I ran `kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha` before running `kubectl create -f providerconfig-ibm-cloud.yaml`

`kubectl get crds | grep ibm-cloud` returns **nothing**.

--
I created a brand new OpenShift cluster (latest version) on IBM Cloud, then I installed Crossplane as per [these instructions](https://crossplane.io/docs/v1.0/getting-started/install-configure.html) for self-hosted, via Helm 3 (stable).

Then, I followed [the IBM provider install instructions](https://github.com/crossplane-contrib/provider-ibm-cloud) instructions including both as `cat ..` from command line and as `apply` or `create` via file.

Also, FYI
```
$ oc version
Client Version: 4.4.0-202005290638-1960dd7
Server Version: 4.5.24
Kubernetes Version: v1.18.3+fa69cae
```

**Comment by pdettori** [comment]
it looks like the provider did not get installed, or at least that the CRDs for the provider are not installed, therefore the providerconfig cannot be applied. To check on the installation of the provider, could you please run:

```shell
kubectl describe provider/provider-ibm-cloud
```

**Comment by cg2p** [comment]
```
$ kubectl describe provider/provider-ibm-cloud
Error from server (NotFound): providers.pkg.crossplane.io "provider-ibm-cloud" not found
```

**Comment by pdettori** [comment]
yeah, it looks something went wrong then with the `kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha` command then. Could you pls. try to check the version of the crossplane plugin you have installed with:

```shell
kubectl crossplane -v
```
If the crossplane plugin is not installed, pls. install it as described [here](https://crossplane.io/docs/v1.0/getting-started/install-configure.html#install-crossplane-cli). If you still have issues, you may also try to directly apply the provider using the following yaml:

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-ibm-cloud
spec:
  ignoreCrossplaneConstraints: false
  package: crossplane/provider-ibm-cloud:alpha
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
```

**Comment by cg2p** [comment]
hmm ok so repeated some steps:

CLI install
```
curl -sL https://raw.githubusercontent.com/crossplane/crossplane/release-1.0/install.sh | sh
sudo mv kubectl-crossplane /usr/local/bin
kubectl crossplane --help
```

check version and install
```
$ kubectl crossplane -v
v1.0.0
```

retry, same error
```
$ kubectl crossplane install provider crossplane/provider-ibm-cloud:alpha
provider.pkg.crossplane.io/crossplane-provider-ibm-cloud created

kubectl apply -f providerconfig-ibm-cloud.yaml
error: unable to recognize "providerconfig-ibm-cloud.yaml": no matches for kind "ProviderConfig" in version "ibm-cloud.crossplane.io/v1beta1"
```

create a provider yaml file with what you suggest above
```
$ kubectl apply -f provider-ibm.yaml
provider.pkg.crossplane.io/provider-ibm-cloud created

$ kubectl apply -f providerconfig-ibm-cloud.yaml
error: unable to recognize "providerconfig-ibm-cloud.yaml": no matches for kind "ProviderConfig" in version "ibm-cloud.crossplane.io/v1beta1"
```

**Comment by cg2p** [comment]
providerconfig-ibm-cloud.yaml
```
apiVersion: ibm-cloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ibm-cloud
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-ibm-cloud-secret
      key: credentials
  region: us-south  
```

provider-ibm.yaml
```
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-ibm-cloud
spec:
  ignoreCrossplaneConstraints: false
  package: crossplane/provider-ibm-cloud:alpha
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
```

I notice metadata name is different, is that significant?
